import AuthProvider from "@/providers/AuthProvider";
import Providers from "@/providers/Providers";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import "./globals.css";
import { ApolloWrapper } from "@/providers/ApolloWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const supabase = createServerComponentClient({ cookies });

    const {
        data: { session },
    } = await supabase.auth.getSession();

    return (
        <ApolloWrapper session={session}>
            <html lang="en">
                <body className={inter.className}>
                    <AuthProvider session={session} accessToken={session?.access_token}>
                        <Providers>{children}</Providers>
                    </AuthProvider>
                </body>
            </html>
        </ApolloWrapper>
    );
}
